### ISSUE TITLE
DiffuserCam images of natural objects

### ISSUE THREAD

**Issue by tianjiaozeng** [Waller-Lab/LenslessLearning#2]
Thanks for sharing the code as well as the training dataset.
I've read your papers and I'm really interested in your work. I noticed that you also tested your network on objects in the wild captured with DiffuserCam but I could find these data on your website.
I'm wondering if these measurements can also be shared. It would be a great help!

Thank you so much!

**Comment by monakhova** [comment]
The in the wild captured images have been added to the Dataset page as well as the readme. Sorry for the delay!
